import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const calendars = [
  {
    slug: 'epl',
    name: 'English Premier League',
    category: 'football',
    sport: 'football',
    description: 'All 380 Premier League fixtures, results and standings for the current season.',
    country: 'england',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'champions-league',
    name: 'UEFA Champions League',
    category: 'football',
    sport: 'football',
    description: "Europe's premier club football competition — from the group stage to the final.",
    country: 'europe',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'la-liga',
    name: 'La Liga',
    category: 'football',
    sport: 'football',
    description: "Spain's top football division featuring FC Barcelona, Real Madrid, and more.",
    country: 'spain',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'world-cup-2026',
    name: 'FIFA World Cup 2026',
    category: 'football',
    sport: 'football',
    description: 'Every match of the 2026 FIFA World Cup hosted across USA, Canada, and Mexico.',
    country: 'global',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'euro',
    name: 'UEFA European Championship',
    category: 'football',
    sport: 'football',
    description: "The UEFA European Championship — the continent's biggest international tournament.",
    country: 'europe',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'bundesliga',
    name: 'Bundesliga',
    category: 'football',
    sport: 'football',
    description: "Germany's top-flight football league, home of Bayern Munich and Borussia Dortmund.",
    country: 'germany',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'serie-a',
    name: 'Serie A',
    category: 'football',
    sport: 'football',
    description: "Italy's premier football division — Inter Milan, Juventus, AC Milan and more.",
    country: 'italy',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'super-eagles',
    name: 'Nigeria Super Eagles',
    category: 'football',
    sport: 'football',
    description: "Full schedule of Nigeria's national football team — friendlies, qualifiers, tournaments.",
    country: 'nigeria',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'npfl',
    name: 'Nigerian Premier Football League',
    category: 'football',
    sport: 'football',
    description: "Nigeria's domestic top-flight football league — all clubs, all fixtures.",
    country: 'nigeria',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'afcon',
    name: 'Africa Cup of Nations',
    category: 'football',
    sport: 'football',
    description: "Africa's most prestigious international football tournament.",
    country: 'africa',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'formula-1',
    name: 'Formula 1',
    category: 'f1',
    sport: 'motorsport',
    description: 'Every F1 session — practice, qualifying, sprint, and race — for the full season.',
    country: 'global',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'nba',
    name: 'NBA Basketball',
    category: 'basketball',
    sport: 'basketball',
    description: 'NBA regular season, playoffs, and Finals fixtures for all 30 teams.',
    country: 'global',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'boxing',
    name: 'World Championship Boxing',
    category: 'boxing',
    sport: 'boxing',
    description: 'IBF, WBA, WBC and WBO world title fights — never miss a championship bout.',
    country: 'global',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'bbnnaija',
    name: 'Big Brother Naija',
    category: 'entertainment',
    sport: null,
    description: "Nigeria's biggest reality TV show — eviction nights, finale dates, and live events.",
    country: 'nigeria',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'afrobeats-tours',
    name: 'Afrobeats Concert Tours',
    category: 'entertainment',
    sport: null,
    description: 'Afrobeats concert tours and live performances from Burna Boy, Wizkid, Davido, and more.',
    country: 'global',
    isFeatured: false,
    iconUrl: null,
  },
  {
    slug: 'upcoming-movies',
    name: 'Upcoming Movies',
    category: 'tv',
    sport: null,
    description: 'Theatrical releases and streaming premieres — blockbusters, indies, and Nollywood.',
    country: 'global',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'tv-episodes',
    name: 'TV Episode Air Dates',
    category: 'tv',
    sport: null,
    description: 'Weekly episode drops and finales for the shows you follow — HBO, Netflix, Disney+, and more.',
    country: 'global',
    isFeatured: true,
    iconUrl: null,
  },
  {
    slug: 'new-series',
    name: 'New Series & Seasons',
    category: 'tv',
    sport: null,
    description: 'Series premieres and new season launches — never miss a debut episode.',
    country: 'global',
    isFeatured: false,
    iconUrl: null,
  },
]

async function main() {
  console.log('Seeding calendars...')
  for (const cal of calendars) {
    await prisma.calendar.upsert({
      where: { slug: cal.slug },
      update: {
        name: cal.name,
        category: cal.category,
        sport: cal.sport,
        description: cal.description,
        country: cal.country,
        isFeatured: cal.isFeatured,
        iconUrl: cal.iconUrl,
      },
      create: cal,
    })
    console.log(`  ✓ ${cal.name}`)
  }
  console.log('Done.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
